export const copy = {
  en: {
    listen: "Listen",
    music: "Music",
    hello: "Hello",
    body: "I write songs and build the sound around them.",
    after: "Guitar, voice, everything after.",
    track: "Gold in the Dark",
    note: "The new track.",
    songs: "01 / Songs & sessions",
    aside: "Guitar. Voice. Everything after.",
    feelingTitle: "It starts",
    feelingBreak: "with a feeling.",
    feeling:
      "I sing and write in English and Spanish, on guitar and piano. As I build the production, I want to keep what made the first take feel honest.",
    mixA: "Guitars up front. Drums underneath.",
    mixB: "Room for what I need to say.",
    workbenchName: "MaloSound",
    workbench: "The workbench. Recording and sound. Songs first.",
    about: "About",
    familiar: "My mom calls me Chelo. People call me Marcy.",
    aboutBody: "I love putting what I feel into music.",
    last: "Last screen",
    helloBody: "Songs, a collab, a note.",
  },
  es: {
    listen: "Escuchar",
    music: "Música",
    hello: "Hola",
    body: "Escribo canciones y construyo el sonido alrededor.",
    after: "Guitarra, voz, todo lo que sigue.",
    track: "Gold in the Dark",
    note: "El tema nuevo.",
    songs: "01 / Canciones y sesiones",
    aside: "Guitarra. Voz. Todo lo que sigue.",
    feelingTitle: "Empieza",
    feelingBreak: "con un sentimiento.",
    feeling:
      "Canto y escribo en inglés y en español, en guitarra y piano. Mientras armo la producción, quiero conservar lo que hizo honesta la primera toma.",
    mixA: "Guitarras al frente. Batería debajo.",
    mixB: "Espacio para lo que necesito decir.",
    workbenchName: "MaloSound",
    workbench: "El taller. Grabación y sonido. Primero las canciones.",
    about: "Sobre mí",
    familiar: "Mi mamá me dice Chelo. La gente me dice Marcy.",
    aboutBody: "Me encanta poner lo que siento en la música.",
    last: "Última pantalla",
    helloBody: "Canciones, un collab, una nota.",
  },
} as const;

export type Lang = keyof typeof copy;
